import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { createRoot } from "react-dom/client";
import { HelmetProvider } from "react-helmet-async";
import i18n from "./i18n";
import "@styles/globals.scss";
import { BrowserRouter, Route, Routes } from "react-router-dom";
import { I18nextProvider } from "react-i18next";
import { Layout } from "./pages/Layout";
import { TermsAndConditions } from "./pages/terms-and-conditions";
import { Home } from "./pages/home/Home";
import { Gallery } from "./pages/gallery/Gallery";
import { NotFound } from "./pages/not-found";
import { Analytics } from "@vercel/analytics/react";
createRoot(document.getElementById("root")).render(_jsxs(BrowserRouter, { children: [_jsx(Analytics, {}), _jsx(I18nextProvider, { i18n: i18n, children: _jsx(HelmetProvider, { children: _jsxs(Routes, { children: [_jsxs(Route, { path: "/", element: _jsx(Layout, {}), children: [_jsx(Route, { index: true, element: _jsx(Home, {}) }), _jsx(Route, { path: "gallery", element: _jsx(Gallery, {}) }), _jsx(Route, { path: "terms-and-conditions", element: _jsx(TermsAndConditions, {}) }), _jsx(Route, { path: "return-policy", element: _jsx(TermsAndConditions, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] }), _jsxs(Route, { path: "/:lang", element: _jsx(Layout, {}), children: [_jsx(Route, { index: true, element: _jsx(Home, {}) }), _jsx(Route, { path: "gallery", element: _jsx(Gallery, {}) }), _jsx(Route, { path: "terms-and-conditions", element: _jsx(TermsAndConditions, {}) }), _jsx(Route, { path: "return-policy", element: _jsx(TermsAndConditions, {}) }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] })] }) }) })] }));
